# Generated by Django 2.2.7 on 2019-11-28 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lastused', models.DateTimeField(default=datetime.datetime.now)),
                ('apikey', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Werktijd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=20)),
                ('achternaam', models.CharField(max_length=20)),
                ('begintijd', models.TimeField()),
                ('eindtijd', models.TimeField()),
                ('datum', models.DateField()),
                ('pauze', models.TimeField()),
                ('extra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favoriet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_voornaam', models.CharField(max_length=20)),
                ('f_achternaam', models.CharField(max_length=20)),
                ('eigenaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
