# Generated by Django 2.2.7 on 2019-12-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PlanningViewer', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='werktijd',
            name='colors',
            field=models.CharField(default='[]', max_length=50),
        ),
    ]
