# Generated by Django 3.0.6 on 2020-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningViewer', '0004_werktijd_overwerk'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriet',
            name='show_marker',
            field=models.BooleanField(default=False),
        ),
    ]
