# Generated by Django 3.0.6 on 2020-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningViewer', '0005_favoriet_show_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriet',
            name='show_tab',
            field=models.BooleanField(default=True),
        ),
    ]
