# Generated by Django 3.1.2 on 2020-10-16 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningViewer', '0006_favoriet_show_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='contract_uren',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='start_contract_uren',
            field=models.DateField(default=datetime.date(2020, 9, 7)),
        ),
    ]
