# Generated by Django 3.1.2 on 2020-11-11 15:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlanningViewer', '0007_auto_20201016_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverurenAjust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(2019)])),
                ('periode', models.IntegerField(validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(1)])),
                ('uren_change', models.FloatField(default=0.0)),
                ('reason', models.CharField(choices=[('UB', 'Uitbetaling'), ('CC', 'Correctie')], default='UB', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
