# Generated by Django 4.1 on 2022-09-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningViewer', '0011_mutatie_alter_overurenajust_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mutatie',
        ),
        migrations.AlterField(
            model_name='werktijd',
            name='achternaam',
            field=models.CharField(max_length=30),
        ),
    ]
