# Generated by Django 4.1.7 on 2023-02-24 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PlanningViewer', '0012_delete_mutatie_alter_werktijd_achternaam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overurenajust',
            name='year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2030),
                                                                django.core.validators.MinValueValidator(2019)]),
        ),
    ]
